language: node_js
node_js: '13'
dist: bionic
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.12.0'
    - node_js: '13'
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      # If this fails during a PR, CI will fail. However when CI fails, codecov
      # does not post any comment. Since codecov comments are nicer than
      # Travis Buddy comments for this, we skip it during PRs. Also this makes
      # PRs checks faster.
      if: type != pull_request
      script: gulp coverage
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: '1zs6K3T2TOKCBjsTeF1AYglNSIbnuPe7YfJ9lZ7HTWi79qfr8eicOpLcWSMFaUnvmDh7rp0Vk1coNk1CmhXY6yspj2tCebzKfdFIm7rCbUSwBOiOMwq0hcw72anR+CZYYaYoMP8XMfmtXh9rX3hYTrkxxIQ1OLcZrTh6PDy5ALhYKSY8RF3qWUm6lttEOG4v+ly0liiEbA6lvvi6xZoitGdSMWuEU4J/vSPFCqJRJVbqa6ydR8qzutszrTGx0pUp4xfAMnEWq0lgIcvkUmOUtpLul6mDy+s6O5E+Wg9Fj/HT+GTSzox06Pprr3hH0vmv6nvTk2ePKfm7dRhnzONr8dP1SvMbYLOqb7UlmM49JcpZixBdnqk0a0ezBAXwO1o6OewMGeAv5bgizJ6ebzlQnPbc2F+SqMuVJARbvYtyGaiEDjQ2qyGnWbnyUVteq9FdEg3SBMxkE1si0srTfn9p0nIvgW35EJHeyPbrlEJxiyaaS/2cBhINTI1IBuQ6LvEE+fjnmVQbMSBrAzgMEEam+pWF3A8QHC0crLRi2N0nSPmKkcLkIvy4keLBXhouoqVypCIzdUfjo+D2a7VFUcFKKMawNd6yMDMpeBGnwjCnsOwLn8TV6H+TfJB71taGlkdAP0UMumeS971EDunWc2XQezze8gduh3uuNcq8rzFxSfs='
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
